version: '3.7'

services:
  pps:
    build: .
    volumes:
      - ./media:/home/plus-premios-sorteios/media/
    ports:
      - 80:80
    depends_on:
      - database
    environment:
      - RAFFLE_DATABASE=postgres://pps:pps@database:5432/pps
  database:
    image: postgres:12-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pps
      - POSTGRES_PASSWORD=pps
      - POSTGRES_DB=pps

volumes:
  database: