# Generated by Django 3.1 on 2021-04-15 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortition.raffle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotas', models.IntegerField(default=1000, verbose_name='Número de Cotas')),
                ('date', models.DateTimeField(verbose_name='Data do Sorteio')),
                ('winner', models.IntegerField(default=0, verbose_name='Vencedor')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sortition.raffle.models.get_upload_to, verbose_name='Imagem de Perfil')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Numero')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('reserved', 'Reservado'), ('paid', 'Pago')], default='open', max_length=8, verbose_name='Status')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
                ('raffle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raffle.raffle', verbose_name='Rifa')),
            ],
            options={
                'verbose_name': 'Cota',
                'verbose_name_plural': 'Cotas',
            },
        ),
    ]
