# Generated by Django 3.1 on 2021-05-31 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sortition.raffle.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Titulo do Sorteio')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Sorteio')),
                ('quotas', models.IntegerField(default=100, verbose_name='Número de Cotas')),
                ('quota_value', models.CharField(default='R$ 100,00', max_length=10, verbose_name='Valor Unitário da Cota')),
                ('date', models.DateTimeField(verbose_name='Data do Sorteio')),
                ('sorted_quota', models.IntegerField(blank=True, null=True, verbose_name='Cota Sorteada')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sortition.raffle.models.get_upload_to, verbose_name='Imagem Ilustrativa do Sorteio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Criador')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_set', to=settings.AUTH_USER_MODEL, verbose_name='Vencedor')),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
            },
        ),
        migrations.CreateModel(
            name='QuotaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='R$ 100,00', max_length=10, verbose_name='Valor da Reserva')),
                ('status', models.CharField(choices=[('reserved', 'Reservado'), ('paid', 'Pago')], default='reserved', max_length=8, verbose_name='Status')),
                ('reserved_at', models.DateTimeField(auto_now_add=True, verbose_name='Reservado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dono')),
            ],
            options={
                'verbose_name': 'Reserva de Cota',
                'verbose_name_plural': 'Reservas de Cotas',
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Numero')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raffle.quotaorder', verbose_name='Reserva de Cota')),
                ('raffle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='raffle.raffle', verbose_name='Rifa')),
            ],
            options={
                'verbose_name': 'Cota',
                'verbose_name_plural': 'Cotas',
            },
        ),
    ]
