# Generated by Django 3.1 on 2021-04-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Sorteio'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Titulo do Sorteio'),
        ),
    ]
