# Generated by Django 3.1 on 2021-06-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dono Titular'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Sorteio'),
        ),
    ]
