# Generated by Django 3.1 on 2021-05-12 21:02

from django.db import migrations, models
import sortition.raffle.models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0002_auto_20210422_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='quota_value',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Valor Unitário da Cota'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sortition.raffle.models.get_upload_to, verbose_name='Imagem Ilustrativa do Sorteio'),
        ),
    ]
