# Generated by Django 3.1 on 2021-05-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0003_auto_20210512_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='quota_value',
            field=models.CharField(default='R$ 100,00', max_length=10, verbose_name='Valor Unitário da Cota'),
        ),
    ]
