# Generated by Django 3.1 on 2021-05-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0004_auto_20210512_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pago em'),
        ),
        migrations.AddField(
            model_name='quota',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reservado em'),
        ),
    ]
