# Generated by Django 3.1 on 2021-05-29 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raffle', '0005_auto_20210513_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_set', to=settings.AUTH_USER_MODEL, verbose_name='Criador'),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_set', to=settings.AUTH_USER_MODEL, verbose_name='Vencedor'),
        ),
    ]
