# Generated by Django 3.1 on 2021-06-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(max_length=15, unique=True, verbose_name='Whatsapp'),
        ),
    ]
